export { QUESTIONS, PHILOSOPHER_TYPES } from './data'
export type { PhilosopherKey, PhilosopherType, Question, AnswerChoice } from './data'
export { calculateResult } from './score'
export { getMbtiMapping } from './mbti'
export type { MbtiMapping } from './mbti'
