export { QUESTIONS, PHILOSOPHER_TYPES } from './data'
export type { PhilosopherKey, PhilosopherType, Question, AnswerChoice } from './data'
export { calculateResult } from './score'
export { getSajuInfo } from './saju'
export type { SajuInfo } from './saju'
